### ISSUE TITLE
Anndata object with a sparse matrix doesn't work 

### ISSUE THREAD

**Issue by sm2695** [JonETJakobsson/scConnect#1]
Hi, 

I tried running the function cn.genecall.meanExpression, with a previously created Anndata object (n_obs × n_vars = 408 × 25738), and got an error at --> 'df = pd.DataFrame(data, index=idx, columns=col)'

"ValueError: Shape of passed values is (25738, 1), indices imply (25738, 408)"

It seems like this was due to the variable 'data' being a sparse matrix.  Converting it to a dense matrix worked for me. 

adata.X=adata.X.todense()

Hope this helps!

**Comment by JonETJakobsson** [comment]
Hi!

Thank you Susmita for reporting this! I will implement a check to assess type of the matrix and solve this quietly. Your solution should do the trick nicely.

**Comment by JonETJakobsson** [comment]
Fix is now implemented on master and will go live on version 1.0.4.
